#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Plugin-Type
version:      0.01
version_from: Type.pm
installdirs:  site
requires:
    Class::DBI:                    0
    DBI:                           0.94

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
